Layout/ClassStructure:
  Enabled: true

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/LineLength:
  Max: 150
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'lib/generators/**/*'
    - 'lib/templates/**/*'
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'lib/generators/**/*'
    - 'lib/templates/**/*'
    - 'spec/**/*'

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'lib/generators/**/*'
    - 'lib/templates/**/*'
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'lib/generators/**/*'
    - 'lib/templates/**/*'
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'lib/generators/**/*'
    - 'lib/templates/**/*'
    - 'spec/**/*'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'lib/generators/**/*'
    - 'lib/templates/**/*'
    - 'spec/**/*'

Naming/ConstantName:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/DateTime:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: true
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/generators/**/*'
    - 'lib/templates/**/*'
    - 'spec/**/*'

Style/Encoding:
  Enabled: false

Style/GuardClause:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/InlineComment:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods: ['gem', 'render', 'require', 'require_relative', 'source']

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/MissingElse:
  Enabled: true
  EnforcedStyle: 'case'

Style/MultilineMethodSignature:
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/StringHashKeys:
  Enabled: true
  Exclude:
    - 'spec/support/**/*'
